services:
  # Frontend React App
  - type: web
    name: news-dashboard-frontend
    env: static
    buildCommand: cd frontend && npm ci --production=false && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend Flask API
  - type: web
    name: news-dashboard-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: NEWS_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://news-dashboard-frontend.onrender.com
